- app/controllers/pugin/application_controller.rb
- config/initializers/constants.rb
Added engine method within application.rb
> Added engine method

- app/assets/stylesheets/_application.scss
- app/assets/stylesheets/objects/_grid.scss
- app/assets/stylesheets/settings/_breakpoints.scss
CSS Grid added into application builder
CSS breakpoints removed from Grid and centralised in Breakpoints
> CSS amendments

- app/views/layouts/pugin/modules/_profile-card.html.slim
- spec/controllers/application_controller_spec.rb
- test/dummy/app/controllers/application_controller.rb
- test/dummy/app/views/layouts/pugin/modules/_profile-card.html.slim
- test/dummy/config/routes.rb
Ignored the test older
Added new tests
Adjusted test routes file to work with new tests 
cloned view of profile into dummy
> ignored test folder, added tests, adjusted parts of dummy files

- app/helpers/pugin/application_helper.rb
- app/views/layouts/pugin/modules/_card.html.slim
- app/views/layouts/pugin/modules/_contact.html.slim
- app/views/layouts/pugin/modules/_info-block.html.slim
- app/views/layouts/pugin/modules/_test.html.erb
refactoring to helper and partials, removed unnecessary partials, added info block
> Do you believe in life after love 

- app/assets/stylesheets/elements/_form.scss
- app/assets/stylesheets/elements/_media.scss
Element had insufficient contrast for WCAG 2.0 AA conformance level.
> STYLE-42, Accessibility testing

- app/views/pugin/components/_status.html.haml
- app/views/pugin/layouts/pugin.html.haml
- spec/views/pugin/components/_status.html.haml_spec.rb
* added no-js class to body tag
* added url to s3 asset
> [WEBSITE-549] Update path to Javascript within parliament.uk-prototype

- app/views/pugin/layouts/pugin.html.haml
* added X-UA-Compatible meta to header
> [WEBSITE-556] Force latest IE rendering engine

- app/views/pugin/layouts/pugin.html.haml
> [WEBSITE-607] Removed back to top links.

- app/views/pugin/layouts/pugin.html.haml
> [WEBSITE-630]-create a release for parliament.uk-pugin

- app/views/pugin/layouts/pugin.html.haml
> [WEBSITE-630] Create a release for parliament.uk-pugin

- app/views/pugin/components/_footer.html.haml
- app/views/pugin/components/_header.html.haml
- app/views/pugin/layouts/pugin.html.haml
- spec/views/pugin/components/_footer.html.haml_spec.rb
- spec/views/pugin/components/_header.html.haml_spec.rb
[WEBSITE-316] applied version to src paths
> [WEBSITE-316] applied version to src paths

- README.md
Amended previous Pugin references to pugin-components-rails
> [WEBSITE-384] Ensure all READMEs are up to date

- app/views/pugin/components/_status.html.haml
- spec/views/pugin/components/_status.html.haml_spec.rb
- 'full stop' added to banner text.
- Rspec test for banner updated.
> WEBSITE-778 Banner text and associated test updated.

- README.md
- app/views/pugin/components/_header.html.haml
- app/views/pugin/layouts/pugin.html.haml
- lib/pugin/version.rb
- spec/views/pugin/components/_header.html.haml_spec.rb
[WEBSITE-790] Gem reference update and fix to broken link
[WEBSITE-806] Header markup update
[WEBSITE-813] Point to asset location ENV directly and added asset version to version.rb
> [WEBSITE-790][WEBSITE-806][WEBSITE-813] updates to gems / header / envs

- lib/pugin/version.rb
> [WEBSITE-834] updated version dependencies

- Gemfile.lock
- app/views/pugin/cards/_person-list.html.haml
- config/locales/en.yml
- lib/pugin/version.rb
- spec/views/pugin/cards/_person-list.html.haml_spec.rb
- #### Expanded on person-list component
- #### Tests included
> [WEBSITE-795] custom error handling component

- Gemfile.lock
- app/views/pugin/layouts/pugin.html.haml
- lib/pugin.rb
- lib/pugin/version.rb
* Added asset location url to pugin.rb
* Referenced local gtm key
* Bump up of pugin-components-rails version prep for release
> [WEBSITE-932] Pugin and gtm env management updates

- Gemfile.lock
- [Release] Version bump up for pugin and pugin-components
- [Fix] added in new link for feedback form
> [HOTFIX][Release] Gemfile.lock rebuilt

- Gemfile.lock
- app/views/pugin/components/_letter-navigation.html.haml
- lib/pugin/version.rb
- [WEBSITE-984] Update navigation-letter markup
> [Release] Bump up of component-rails version

- app/views/pugin/components/_navigation-main.haml
- app/views/pugin/layouts/pugin.haml
- config/locales/en.yml
- spec/views/pugin/components/_navigation-main.haml_spec.rb
* added main navigation component
* added tests for main navigation component
* updated the locale file to reflect changes
> [WEBSITE-1074][WEBSITE-1076] Main navigation

- app/views/pugin/cards/_person-list.haml
- app/views/pugin/constituencies/list/_list.html.haml
- app/views/pugin/constituencies/list/current/_current_constituency.html.haml
- app/views/pugin/constituencies/list/former/_former_constituency.html.haml
- app/views/pugin/elements/_list.html.haml
- config/locales/en.yml
- lib/pugin.rb
- spec/views/pugin/cards/_person-list.html.haml_spec.rb
and associated views to handle empty object
> [WEBSITE-1142] Update People list partial

- app/views/pugin/components/_navigation-letter.haml
- spec/views/pugin/components/_navigation-letter.html.haml_spec.rb
* Hide a-z navigation when letters object is empty
* Update letter navigation tests
> [WEBSITE-1231] Hide a-z nav when letters object is empty

- app/views/pugin/components/_navigation-letter.haml
- app/views/pugin/people/list/member/_member.html.haml
- config/locales/en.yml
- lib/pugin.rb
- spec/views/pugin/people/list/member/_member.html.haml
Removed usage of word current
bumped version
changed navigation-letter to an ordered list 
Updated partial to use different I18n translation
> [WEBSITE-1480][WEBSITE-1484] Bug fixes

- app/views/pugin/people/list/lord/_lord.html.haml
- app/views/pugin/people/list/member/_member.html.haml
* updated html for rendering member photos
> [WEBSITE-1509] [WEBSITE-1515] Members photos

- app/views/pugin/components/_navigation-main.haml
- lib/pugin/railtie.rb
- spec/views/pugin/components/_navigation-main.html.haml_spec.rb
- spec/views/pugin/layouts/_layout.html.haml_spec.rb
* Updated HousesHelper to reference Parliament::Utils::Helpers::HousesHelper
* Mocked Parliament::Utils::Helpers::ApplicationHelper in tests
> [WEBDEV-43] Extract Helper methods into parliament-utils gem

- app/views/pugin/components/_navigation-letter.haml
- spec/views/pugin/layouts/_layout.html.haml_spec.rb
* Amended navigation-letter partial view
> [WEBSITE-1886] Removed duplicate A-Z text

- lib/pugin/feature/bandiera.rb
- spec/lib/pugin/feature/bandiera_spec.rb
* Added government roles to bandiera module
* Added tests
> [WEBSITE-2031] Add government roles

- lib/pugin/feature/bandiera.rb
- lib/pugin/version.rb
- spec/lib/pugin/feature/bandiera_spec.rb
* Added methods for show-opposition-roles bandiera flag.
* Updated specs
* Bumped version
> Added bandiera flag methods for opposition roles

- config/locales/en.yml
- lib/pugin/version.rb
- spec/views/pugin/people/list/member/_member.html.haml_spec.rb
* Update default datetime format in en.yml file
* Update tests
> Update translation file to use full month names in dates

- app/views/pugin/layouts/_layout.html.haml
- lib/pugin.rb
- lib/pugin/version.rb
- Version bump
- Add legacy style style sheet
> [RELEASE] Pugin version bump

- app/views/pugin/components/_status.haml
- lib/pugin/version.rb
- Removed beta label from status--banner
- Changed `list--inline` to `p`
- pugin-components-ruby version bump
> Removed Beta label and unordered list from status--banner
